# Generated by Django 5.2.8 on 2025-12-04 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_organization'),
        ('bookings', '0008_create_serviceweeklyavailability_table'),
    ]

    operations = [
    ]
