# Generated by Django 5.2.8 on 2025-12-14 22:37

import accounts.models
import accounts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    # No-op migration: the avatar field and its storage/upload_to were already
    # set up in the squashed initial migration. Keep this file empty so tests
    # that build a test database don't attempt to add the same column twice.
    dependencies = [
        ('accounts', '0005_add_profile_avatar'),
    ]

    operations = [
        # No-op (handled by initial squashed migration)
    ]
