# Generated by Django 5.2.8 on 2025-12-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
