# Generated by Django 5.2.8 on 2026-02-04 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_profile_push_booking_notifications_enabled'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mobilessotoken',
            new_name='accounts_mo_user_id_a1e2e6_idx',
            old_name='accounts_mo_user_id_31c7b0_idx',
        ),
        migrations.RenameIndex(
            model_name='mobilessotoken',
            new_name='accounts_mo_expires_326495_idx',
            old_name='accounts_mo_expires_31b9f6_idx',
        ),
        migrations.RenameIndex(
            model_name='pushdevice',
            new_name='accounts_pu_user_id_998019_idx',
            old_name='accounts_pu_user_id_47eae6_idx',
        ),
        migrations.RenameIndex(
            model_name='pushdevice',
            new_name='accounts_pu_last_se_6b7398_idx',
            old_name='accounts_pu_last_se_5ab0d2_idx',
        ),
    ]
