# Backup of bookings/migrations/0002_booking_organization.py
# Original content preserved

# Generated by Django 5.2.8 on 2025-11-24 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='calendar_app.organization'),
            preserve_default=False,
        ),
    ]
