# Generated by Django 5.2.8 on 2025-12-05 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial_squashed_0002_alter_business_owner_alter_business_timezone_and_more'),
        ('billing', '0002_subscription_fk_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_pm_id', models.CharField(max_length=255, unique=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('last4', models.CharField(blank=True, max_length=8, null=True)),
                ('exp_month', models.IntegerField(blank=True, null=True)),
                ('exp_year', models.IntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='accounts.business')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'is_default'], name='billing_pay_organiz_ad965b_idx')],
            },
        ),
    ]
