# Generated by Django 5.2.8 on 2025-12-05 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='scheduled_change_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='scheduled_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.plan'),
        ),
    ]
