# Generated by Django 5.2.8 on 2025-12-05 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial_squashed_0002_alter_business_owner_alter_business_timezone_and_more'),
        ('billing', '0004_subscription_scheduled_change_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('downgrade', 'Downgrade'), ('upgrade', 'Upgrade'), ('other', 'Other')], default='other', max_length=20)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('amount_cents', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('processed', 'Processed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('card_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('card_last4', models.CharField(blank=True, max_length=8, null=True)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('new_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.plan')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_changes', to='accounts.business')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='billing.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
