# Generated by Django 5.2.8 on 2026-02-27 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_adminundosnapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminundosnapshot',
            new_name='calendar_ap_content_679677_idx',
            old_name='calendar_app_content_2a4088_idx',
        ),
        migrations.RenameIndex(
            model_name='adminundosnapshot',
            new_name='calendar_ap_created_781a9b_idx',
            old_name='calendar_app_created__c60c5c_idx',
        ),
    ]
