"""
Django settings for circlecalproject project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from the project's .env file (if present).
# Using an explicit path avoids surprises when `manage.py` is launched from
# a different working directory.
load_dotenv(dotenv_path=BASE_DIR / '.env', override=False)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# --- Bot protection (Cloudflare Turnstile) ---
# Provide these via environment variables in production:
# - TURNSTILE_SITE_KEY
# - TURNSTILE_SECRET_KEY
# Optional:
# - TURNSTILE_ENABLED=1 (default) / 0
TURNSTILE_SITE_KEY = os.getenv('TURNSTILE_SITE_KEY', '').strip()
TURNSTILE_SECRET_KEY = os.getenv('TURNSTILE_SECRET_KEY', '').strip()
TURNSTILE_ENABLED = os.getenv('TURNSTILE_ENABLED', '1').strip().lower() in ('1', 'true', 'yes', 'on')

# Cloudinary is configured via environment variables (e.g. CLOUDINARY_URL).
# No Django setting is required; our storage adapter reads env vars directly.
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'nonpendant-profligately-tessa.ngrok-free.dev',
]

CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
]

LOGIN_REDIRECT_URL = 'calendar_app:post_login'
LOGOUT_REDIRECT_URL = '/'


# Application definition

# Optionally include the AdminLTE theme packages when available.
# In CI/build environments these packages may not be installed; avoid
# failing import errors by checking availability at runtime.
import importlib
_adminlte_apps = []
try:
    if importlib.util.find_spec('adminlte3') is not None:
        _adminlte_apps = ['adminlte3', 'adminlte3_theme']
except Exception:
    _adminlte_apps = []

_storages_apps = []
try:
    if importlib.util.find_spec('storages') is not None:
        _storages_apps = ['storages']
except Exception:
    _storages_apps = []

INSTALLED_APPS = [
    # Admin LTE theme (only if installed)
    *_adminlte_apps,
    # Optional storage backends (e.g., Google Cloud Storage via django-storages)
    *_storages_apps,
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 2FA / OTP
    'django_otp',
    'django_otp.plugins.otp_static',
    'django_otp.plugins.otp_totp',
    # Ensure our templates override third-party ones by placing local app first
    'calendar_app',
    'two_factor',
    # Security
    'axes',
    # Local apps
    'bookings',
    'accounts',
    'billing',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'calendar_app.middleware.AdminPinMiddleware',
    'calendar_app.middleware.CustomDomainMiddleware',
    'calendar_app.middleware.CanonicalHostRedirectMiddleware',
    'calendar_app.middleware.BusinessSlugRedirectMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',  # Rate limiting after auth
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'calendar_app.middleware.OrganizationMiddleware',
    # Place timezone middleware AFTER OrganizationMiddleware
    'calendar_app.middleware.UserTimezoneMiddleware',
]

ROOT_URLCONF = 'circlecalproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Expose current membership role for the active organization
                'calendar_app.context_processors.current_membership_role',
            ],
            'builtins': [
                'calendar_app.templatetags.circlecal_filters',
            ],
        },
    },
]

WSGI_APPLICATION = 'circlecalproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Serve files placed in the project-level `static/` directory during development
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Also include the project's `staticfiles/` directory (often used as
# collectstatic output or local assets). This ensures AdminLTE and other
# pre-built assets placed in `staticfiles/` are served in development.
try:
    STATICFILES_DIRS.append(BASE_DIR / 'staticfiles')
except Exception:
    pass

# Directory where `collectstatic` will gather files for production/static serving.
# Use a distinct folder name to avoid colliding with a project-local `staticfiles/`
# directory that we also want to serve during development.
STATIC_ROOT = BASE_DIR / 'collected_static'

# Media files (uploaded user content)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration
# Default to console backend for development, but allow real SMTP by env vars.
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
try:
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
except Exception:
    EMAIL_PORT = 587
_tls_raw = os.getenv('EMAIL_USE_TLS', 'True')
EMAIL_USE_TLS = str(_tls_raw).lower() in ('1', 'true', 'yes', 'on')

# Support either generic Django SMTP vars or Brevo-style vars.
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER') or os.getenv('BREVO_SMTP_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD') or os.getenv('BREVO_SMTP_PASSWORD')
EMAIL_TIMEOUT = 10

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'CircleCal <noreply@circlecal.app>')

# Email address to receive site contact form submissions. Configure via env:
# CONTACT_RECIPIENT=contactcirclecal@gmail.com
CONTACT_RECIPIENT = os.getenv('CONTACT_RECIPIENT')

STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY")
SITE_URL = os.getenv("SITE_URL") or ("http://127.0.0.1:8000" if DEBUG else "http://localhost:8000")

# Optional admin PIN protection. Set via environment variable `ADMIN_PIN`.
ADMIN_PIN = os.getenv('ADMIN_PIN')

# Django Axes (Rate Limiting)
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 0.25  # 15 minutes (in hours)
AXES_LOCKOUT_PARAMETERS = [['username', 'ip_address']]
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_TEMPLATE = None
AUTHENTICATION_BACKENDS = [
    # Custom backend allows login via email or username (preferred first)
    'accounts.backends.EmailOrUsernameModelBackend',
    # Ensure a backend that implements `get_user` is available for session
    'django.contrib.auth.backends.ModelBackend',  # Default Django auth
    # Use AxesBackend which delegates get_user properly and wraps authentication.
    'axes.backends.AxesBackend',  # Axes lockout check
]