"""
Django settings for circlecalproject project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from the project's .env file (if present).
# Using an explicit path avoids surprises when `manage.py` is launched from
# a different working directory.
load_dotenv(dotenv_path=BASE_DIR / '.env', override=False)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# --- Bot protection (Cloudflare Turnstile) ---
# Provide these via environment variables in production:
# - TURNSTILE_SITE_KEY
# - TURNSTILE_SECRET_KEY
# Optional:
# - TURNSTILE_ENABLED=1 (default) / 0
TURNSTILE_SITE_KEY = os.getenv('TURNSTILE_SITE_KEY', '').strip()
TURNSTILE_SECRET_KEY = os.getenv('TURNSTILE_SECRET_KEY', '').strip()
TURNSTILE_ENABLED = os.getenv('TURNSTILE_ENABLED', '1').strip().lower() in ('1', 'true', 'yes', 'on')

# --- Push notifications (Expo) ---
# The mobile app registers Expo push tokens to the backend.
# Server-side sending is best-effort and should be explicitly enabled.
EXPO_PUSH_ENABLED = os.getenv('EXPO_PUSH_ENABLED', '0').strip().lower() in ('1', 'true', 'yes', 'on')
EXPO_PUSH_URL = os.getenv('EXPO_PUSH_URL', 'https://exp.host/--/api/v2/push/send').strip() or 'https://exp.host/--/api/v2/push/send'

# Cloudinary is configured via environment variables (e.g. CLOUDINARY_URL).
# No Django setting is required; our storage adapter reads env vars directly.
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    # Allow ngrok-hosted dev tunnels.
    '.ngrok-free.app',
    '.ngrok-free.dev',
    '.ngrok.io',
    'nonpendant-profligately-tessa.ngrok-free.dev',
]

CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    # Allow ngrok-hosted dev tunnels.
    'https://*.ngrok-free.app',
    'https://*.ngrok-free.dev',
    'https://*.ngrok.io',
]

LOGIN_REDIRECT_URL = 'calendar_app:post_login'
LOGOUT_REDIRECT_URL = '/'


# --- API / Mobile readiness ---
# React Native native clients generally do not require CORS (they are not a
# browser and do not enforce it), but enabling CORS helps for Expo Web and any
# future web clients.



# Application definition

# Optionally include the Unfold admin UI theme package when available.
# This project has migrated off AdminLTE; do not fall back to it.
# In CI/build environments this package may not be installed; avoid
# failing import errors by checking availability at runtime.
import importlib
_admin_theme_apps = []
try:
    if importlib.util.find_spec('unfold') is not None:
        _admin_theme_apps = ['unfold']
except Exception:
    _admin_theme_apps = []

_storages_apps = []
try:
    if importlib.util.find_spec('storages') is not None:
        _storages_apps = ['storages']
except Exception:
    _storages_apps = []

_cors_apps = []
try:
    if importlib.util.find_spec('corsheaders') is not None:
        _cors_apps = ['corsheaders']
except Exception:
    _cors_apps = []

_api_apps = []
try:
    if importlib.util.find_spec('rest_framework') is not None:
        _api_apps.append('rest_framework')
except Exception:
    pass

try:
    if importlib.util.find_spec('rest_framework_simplejwt') is not None:
        _api_apps.append('rest_framework_simplejwt')
except Exception:
    pass

INSTALLED_APPS = [
    # Admin UI theme (only if installed)
    *_admin_theme_apps,
    # Optional storage backends (e.g., Google Cloud Storage via django-storages)
    *_storages_apps,
    # Optional CORS + API libs (used by mobile/web clients)
    *_cors_apps,
    *_api_apps,
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 2FA / OTP
    'django_otp',
    'django_otp.plugins.otp_static',
    'django_otp.plugins.otp_totp',
    # Ensure our templates override third-party ones by placing local app first
    'calendar_app.apps.CalendarAppConfig',
    'two_factor',
    # Security
    'axes',
    # Local apps
    'bookings',
    'accounts',
    'billing',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Must be near the top, especially before CommonMiddleware
    *(('corsheaders.middleware.CorsMiddleware',) if _cors_apps else ()),
    'django.contrib.sessions.middleware.SessionMiddleware',
    'calendar_app.middleware.AppModeMiddleware',
    'calendar_app.middleware.AdminPinMiddleware',
    'calendar_app.middleware.CustomDomainMiddleware',
    'calendar_app.middleware.CanonicalHostRedirectMiddleware',
    'calendar_app.middleware.BusinessSlugRedirectMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'calendar_app.middleware.AdminUndoContextMiddleware',
    'axes.middleware.AxesMiddleware',  # Rate limiting after auth
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'calendar_app.middleware.OrganizationMiddleware',
    # Place timezone middleware AFTER OrganizationMiddleware
    'calendar_app.middleware.UserTimezoneMiddleware',
]

if _cors_apps:
    CORS_ALLOWED_ORIGINS = [
        'https://circlecal.app',
        'https://www.circlecal.app',
        'http://localhost:3000',
        'http://127.0.0.1:3000',
        'http://localhost:19006',
        'http://127.0.0.1:19006',
    ]

if 'rest_framework' in _api_apps:
    _has_simplejwt = 'rest_framework_simplejwt' in _api_apps
    _auth_classes = [
        'rest_framework.authentication.SessionAuthentication',
    ]
    if _has_simplejwt:
        _auth_classes.insert(0, 'rest_framework_simplejwt.authentication.JWTAuthentication')

    REST_FRAMEWORK = {
        'DEFAULT_AUTHENTICATION_CLASSES': [
            *_auth_classes,
        ],
        # Protect endpoints explicitly (per-view) to avoid surprises.
        'DEFAULT_PERMISSION_CLASSES': [
            'rest_framework.permissions.AllowAny',
        ],
    }

ROOT_URLCONF = 'circlecalproject.urls'


# --- Unfold admin configuration ---
# Keep this minimal: just expose custom admin pages in the sidebar.
# All models remain accessible via the "All applications" drawer.
UNFOLD = {
    "SITE_TITLE": "CircleCal Database",
    "SITE_HEADER": "CircleCal Database",
    "SITE_ICON": {
        "light": "/static/icons/circlecalicon.png",
        "dark": "/static/icons/circlecalicon.png",
    },
    "COLORS": {
        # Global neutrals (used for most of the UI backgrounds/borders/text).
        # This is what changes the *overall* look of the admin.
        # Keep this neutral so the layout stays clean/white.
        "base": {
            "50": "#FFFFFF",
            "100": "#F5F5F5",
            "200": "#E5E5E5",
            "300": "#D4D4D4",
            "400": "#A3A3A3",
            "500": "#737373",
            "600": "#525252",
            "700": "#404040",
            "800": "#262626",
            "900": "#171717",
            "950": "#000000",
        },
        # Brand primary: CircleCal blue. Accents remain neutral (black/white)
        # via Unfold's default base/font palettes.
        "primary": {
            "50": "#EEF1FF",
            "100": "#DDE3FF",
            "200": "#B8C3FF",
            "300": "#8FA1FF",
            "400": "#5E74FF",
            "500": "#2C45FF",
            "600": "#2236CC",
            "700": "#1F2AA6",
            "800": "#121A66",
            "900": "#0A0A2E",
            "950": "#050516",
        },
    },
    "STYLES": [
        "/static/css/unfold_circlecal.css",
    ],
    "SIDEBAR": {
        "show_search": True,
        "command_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Insights",
                "items": [
                    {
                        "title": "Admin home",
                        "icon": "home",
                        "link": lambda request: reverse_lazy("admin:index"),
                    },
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": lambda request: reverse_lazy("admin_dashboard"),
                    },
                    {
                        "title": "Analytics",
                        "icon": "insights",
                        "link": lambda request: reverse_lazy("admin_analytics"),
                    },
                    {
                        "title": "Undo history",
                        "icon": "history",
                        "link": lambda request: reverse_lazy("admin_undo_history"),
                    },
                ],
            }
        ],
    },
    "COMMAND": {
        "search_models": True,
        "show_history": True,
    },
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Expose current membership role for the active organization
                'calendar_app.context_processors.current_membership_role',
                # App-webview flags (native app vs browser/PWA)
                'calendar_app.context_processors.cc_app_context',
            ],
            'builtins': [
                'calendar_app.templatetags.circlecal_filters',
            ],
        },
    },
]

WSGI_APPLICATION = 'circlecalproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Serve files placed in the project-level `static/` directory during development
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Also include the project's `staticfiles/` directory (often used as
# collectstatic output or local assets).


# Directory where `collectstatic` will gather files for production/static serving.
# Use a distinct folder name to avoid colliding with a project-local `staticfiles/`
# directory that we also want to serve during development.
STATIC_ROOT = BASE_DIR / 'collected_static'

# Media files (uploaded user content)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration
# Default to console backend for development, but allow real SMTP by env vars.
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
try:
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
except Exception:
    EMAIL_PORT = 587
_tls_raw = os.getenv('EMAIL_USE_TLS', 'True')
EMAIL_USE_TLS = str(_tls_raw).lower() in ('1', 'true', 'yes', 'on')

# Support either generic Django SMTP vars or Brevo-style vars.
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER') or os.getenv('BREVO_SMTP_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD') or os.getenv('BREVO_SMTP_PASSWORD')
EMAIL_TIMEOUT = 10

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'CircleCal <noreply@circlecal.app>')

# Where user replies to automated support confirmations should go.
# Example: SUPPORT_EMAIL='CircleCal Support <support@circlecal.app>'
SUPPORT_EMAIL = os.getenv('SUPPORT_EMAIL')

# Email address to receive site contact form submissions. Configure via env:
# CONTACT_RECIPIENT=contactcirclecal@gmail.com
CONTACT_RECIPIENT = os.getenv('CONTACT_RECIPIENT')

STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY")
SITE_URL = os.getenv("SITE_URL") or ("http://127.0.0.1:8000" if DEBUG else "https://circlecal.app")

# Optional admin PIN protection. Set via environment variable `ADMIN_PIN`.
ADMIN_PIN = os.getenv('ADMIN_PIN')

# Admin URL path (security-by-obscurity convenience). Defaults to /admin/.
# Set in production via env var ADMIN_PATH (example: "ops-7f3c9a").
ADMIN_PATH = (os.getenv('ADMIN_PATH') or 'admin').strip().strip('/')

# Django Axes (Rate Limiting)
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 0.25  # 15 minutes (in hours)
AXES_LOCKOUT_PARAMETERS = [['username', 'ip_address']]
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_TEMPLATE = None
# Avoid persisting request GET/POST payloads into the database.
AXES_HANDLER = "circlecalproject.axes_handlers.PrivacyPreservingAxesDatabaseHandler"
AUTHENTICATION_BACKENDS = [
    # Custom backend allows login via email or username (preferred first)
    'accounts.backends.EmailOrUsernameModelBackend',
    # Ensure a backend that implements `get_user` is available for session
    'django.contrib.auth.backends.ModelBackend',  # Default Django auth
    # Use AxesBackend which delegates get_user properly and wraps authentication.
    'axes.backends.AxesBackend',  # Axes lockout check
]