"""Add per-service slot increment and squished-booking settings.

Generated by assistant patch.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_add_allow_ends_after_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='time_increment_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Client-visible slot increment in minutes'),
        ),
        migrations.AddField(
            model_name='service',
            name='use_fixed_increment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='allow_squished_bookings',
            field=models.BooleanField(default=False),
        ),
    ]
