# Generated by Django 5.2.8 on 2025-12-09 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_add_service_slot_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSettingFreeze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('frozen_settings', models.JSONField(default=dict)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting_freezes', to='bookings.service')),
            ],
            options={
                'unique_together': {('service', 'date')},
            },
        ),
    ]
