# Generated by Django 5.2.8 on 2025-12-19 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_organization'),
        ('bookings', '0007_orgsettings_refund_policy'),
        ('bookings', '0008_add_public_ref'),
    ]

    operations = [
    ]
