"""Add ServiceAssignment model to link Services with Memberships.

Generated by assistant.
"""
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ('accounts', '0008_alter_profile_avatar_team_teammembership'),
        ('bookings', '0010_booking_assigned_team_booking_assigned_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='bookings.service')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_assignments', to='accounts.membership')),
            ],
            options={
                'unique_together': {('service', 'membership')},
            },
        ),
    ]
