# Generated by Django 5.2.8 on 2025-12-21 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_profile_display_name'),
        ('bookings', '0011_serviceassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberWeeklyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_availability', to='accounts.membership')),
            ],
            options={
                'ordering': ['membership', 'weekday', 'start_time'],
                'indexes': [models.Index(fields=['membership', 'weekday'], name='bookings_me_members_274439_idx')],
            },
        ),
    ]
