# Generated by Django 5.2.8 on 2025-12-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_facility_resources'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='facilityresource',
            new_name='bookings_fa_organiz_59f1ef_idx',
            old_name='bookings_fa_organiza_d55d7a_idx',
        ),
        migrations.RenameIndex(
            model_name='serviceresource',
            new_name='bookings_se_service_52e35e_idx',
            old_name='bookings_se_service_0d2d2f_idx',
        ),
        migrations.RenameIndex(
            model_name='serviceresource',
            new_name='bookings_se_resourc_375b34_idx',
            old_name='bookings_se_resourc_032caf_idx',
        ),
        migrations.AlterField(
            model_name='facilityresource',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='serviceresource',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
