# Generated by Django 5.2.8 on 2026-01-01 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_profile_display_name'),
        ('bookings', '0016_booking_payment_fields_and_offline_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, db_index=True, default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(blank=True, db_index=True, default='not_required', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rescheduled_from_booking_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='PublicBookingIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('payment_method', models.CharField(blank=True, db_index=True, default='stripe', max_length=20)),
                ('payment_status', models.CharField(blank=True, db_index=True, default='pending', max_length=20)),
                ('stripe_checkout_session_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('rescheduled_from_booking_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_booking_intents', to='accounts.business')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_booking_intents', to='bookings.service')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'created_at'], name='bookings_pu_organiz_2c4300_idx'), models.Index(fields=['service', 'start'], name='bookings_pu_service_5da9b1_idx')],
            },
        ),
    ]
