# Generated by Django 5.2.8 on 2026-01-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_alter_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='allow_stripe_payments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='allowed_offline_payment_methods',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
