# Generated by Django 5.2.8 on 2025-12-04 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_business_owner_alter_business_timezone_and_more'),
        ('bookings', '0009_merge_20251204_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.business'),
        ),
    ]
